name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        JWT_SECRET: ${ secrets.JWT_SECRET }
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
            path: Dynamic-Price-Optimiser  # Ensures single directory layer

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install
        working-directory: ./Dynamic-Price-Optimiser

      - name: Run Tests
        run: npm test
        working-directory: ./Dynamic-Price-Optimiser
